# Demonstration Folder
#experiment_path: "/home/lx/experiments/lx/exp_corrective/" ## this value is unused
#experiment_name: "0311_insertion"

run_name: BC_model
# path to the VINN folder, source folder
dataset: CustomDataset
extension: Custom
root_dir: /home/lx/ha_ws/src/VINN/
folder:  /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/dataset/ # to the image train dir
save_dir: /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/BYOL_Training/

# training configuration
lr: 3e-4  # learning rate
img_size: 224
batch_size: 8
epochs: 1000
wandb: 1
gpu: 1
hidden_layer: avgpool
pretrained: 1
train_representation: 0  # train intermediate representation network

# BC configurations
t: 0
model: BYOL
bc_model: None
train_dir: /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/train_dataset/
val_dir: /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/val_dataset/
representation_model_path: /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/BYOL_Training/InsertionPuzzle_Time1719_Day1411/epoch_300_.pt
layer: avgpool
architecture: ResNet
eval: 0
pretrain_encoder: 1   # pretrained ResNet on ImageNet

