# Demonstration Folder
#experiment_path: "/home/lx/experiments/lx/exp_corrective/" ## this value is unused
#experiment_name: "0311_insertion"

run_name: BYOL
# path to the VINN folder, source folder
dataset: HD5FDataset
extension: Custom
root_dir: /home/lx/ha_ws/src/VINN/
folder:  /home/lx/experiments/lx/act/ACT_Panda/data/insertion_puzzle/ # to the image train dir
save_dir: /home/lx/experiments/lx/act/ACT_Panda/checkpoints/VINN_puzzle/

# training configuration
lr: 3e-4  # learning rate
img_size: 224
batch_size: 8
epochs: 10000
wandb: 1
gpu: 1
hidden_layer: avgpool
pretrained: 1
train_representation: 1  # train intermediate representation network

# BC configurations
bc_model: None