# Demonstration Folder
#experiment_path: "/home/lx/experiments/lx/exp_corrective/" ## this value is unused
#experiment_name: "0311_insertion"

run_name: BC_model
# path to the VINN folder, source folder
dataset: CustomDataset
extension: Custom
root_dir: /home/lx/ha_ws/src/VINN/
folder:  /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/dataset/ # to the image train dir
save_dir: /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/BYOL_Training/

# training configuration
lr: 0.0001  # learning rate
img_size: 224
batch_size: 8
epochs: 10000
wandb: 1
gpu: 1
hidden_layer: avgpool
pretrained: 1
train_representation: 1  # train intermediate representation network

# BC configurations
t: 0
model: BYOL
bc_model: None
train_dir: /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/BC_train_dataset
val_dir: /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/BC_val_dataset
representation_model_path: /home/lx/experiments/lx/exp_corrective/3101InsertionPuzzle/BYOL_Training/InsertionPuzzle_Time812_Day43/epoch_159_best_model.pt
layer: avgpool
architecture: ResNet
eval: 0
pretrain_encoder: 1   # pretrained ResNet on ImageNet

